#!/bin/bash
file="file_path"

if [ -e "$file" ]; then
  echo "$file passwords are enabled."
  if [ -w "$file" ]; then
    echo "You have permissions to edit $file."
  else
    echo "You do NOT have permissions to edit $file."
  fi
else
  echo "$file does not exist."
fi
